import { Category, MainCategory, Product } from './types';
import { 
  Cookie, CupSoda, Milk, Candy, Wheat, Croissant, Utensils, Carrot, 
  Egg, Heart, SprayCan, Bath, Scissors, Baby, Dog, Flame, ShoppingBag,
  Zap
} from 'lucide-react';

// Minimal Categories for HomeScreen to prevent crash
export const CATEGORIES: Category[] = [
  { id: 'c-1', name: 'Snacks', image: 'https://placehold.co/200x200/orange/white?text=Snacks' },
  { id: 'c-2', name: 'Drinks', image: 'https://placehold.co/200x200/blue/white?text=Drinks' },
  { id: 'c-3', name: 'Dairy', image: 'https://placehold.co/200x200/teal/white?text=Dairy' },
  { id: 'c-4', name: 'Veggies', image: 'https://placehold.co/200x200/green/white?text=Veg' },
];

export const CATEGORIES_DB: MainCategory[] = [
  { id: 'snacks', name: 'Snacks & Munchies', icon: Cookie, items: [] },
  { id: 'beverages', name: 'Cold Drinks & Juices', icon: CupSoda, items: [] },
  { id: 'dairy', name: 'Milk, Curd & Paneer', icon: Milk, items: [] },
  { id: 'sweets_chocolates', name: 'Sweets & Chocolates', icon: Candy, items: [] },
  { id: 'staples_flours', name: 'Atta, Rice & Dal', icon: Wheat, items: [] },
  { id: 'bakery_biscuits', name: 'Biscuits & Bakery', icon: Croissant, items: [] },
  { id: 'pantry_spices_sauces', name: 'Masalas & Sauces', icon: Utensils, items: [] },
  { id: 'fresh_produce', name: 'Fruits & Veggies', icon: Carrot, items: [] },
  { id: 'meat_eggs', name: 'Eggs, Meat & Fish', icon: Egg, items: [] },
  { id: 'health_wellness', name: 'Pharma & Wellness', icon: Heart, items: [] },
  { id: 'home_cleaning', name: 'Cleaning Essentials', icon: SprayCan, items: [] },
  { id: 'personal_hygiene', name: 'Bath & Body', icon: Bath, items: [] },
  { id: 'hair_care', name: 'Hair Care', icon: Scissors, items: [] },
  { id: 'baby_care', name: 'Baby Care', icon: Baby, items: [] },
  { id: 'pet_care', name: 'Pet Care', icon: Dog, items: [] },
  { id: 'puja_essentials', name: 'Puja Needs', icon: Flame, items: [] },
];

export const PRODUCT_DB: Product[] = [
  /* --- SNACKS (categoryId: snacks) --- */
  { "id": "sn-1", "categoryId": "snacks", "name": "Lay's India's Magic Masala", "price": 30, "originalPrice": 34, "image": "", "weight": "73g", "discount": "12% OFF" },
  { "id": "sn-2", "categoryId": "snacks", "name": "Cornitos Nacho Crisps - Cheese and Herbs", "price": 95, "originalPrice": 95, "image": "", "weight": "150g", "discount": "" },
  { "id": "sn-3", "categoryId": "snacks", "name": "Haldiram's Aloo Bhujia", "price": 55, "originalPrice": 55, "image": "", "weight": "200g", "discount": "" },
  { "id": "sn-4", "categoryId": "snacks", "name": "Urban Platter Salted Pretzels", "price": 225, "originalPrice": 225, "image": "", "weight": "150g", "discount": "" },
  { "id": "sn-5", "categoryId": "snacks", "name": "Pringles Potato Chips - Sour Cream & Onion", "price": 115, "originalPrice": 115, "image": "", "weight": "107g", "discount": "" },
  { "id": "sn-6", "categoryId": "snacks", "name": "Bingo! Mad Angles Achaari Masti", "price": 25, "originalPrice": 25, "image": "", "weight": "72g", "discount": "" },
  { "id": "sn-7", "categoryId": "snacks", "name": "Too Yumm! Karare - Masala Munch", "price": 20, "originalPrice": 20, "image": "", "weight": "75g", "discount": "" },
  { "id": "sn-8", "categoryId": "snacks", "name": "Bikaji Sub Kuch Namkeen", "price": 60, "originalPrice": 60, "image": "", "weight": "200g", "discount": "" },
  { "id": "sn-9", "categoryId": "snacks", "name": "Too Yumm! Veggie Stix - Chilli Chatka", "price": 20, "originalPrice": 20, "image": "", "weight": "65g", "discount": "" },
  { "id": "sn-10", "categoryId": "snacks", "name": "Bingo! Tedhe Medhe Masala Tadka", "price": 20, "originalPrice": 20, "image": "", "weight": "72g", "discount": "" },
  { "id": "sn-11", "categoryId": "snacks", "name": "Kurkure Masala Munch", "price": 20, "originalPrice": 20, "image": "", "weight": "80g", "discount": "" },
  { "id": "sn-12", "categoryId": "snacks", "name": "Lay's American Style Cream & Onion", "price": 30, "originalPrice": 30, "image": "", "weight": "73g", "discount": "" },

  /* --- BEVERAGES (categoryId: beverages) --- */
  { "id": "bv-1", "categoryId": "beverages", "name": "Coca-Cola Zero Sugar", "price": 45, "originalPrice": 50, "image": "", "weight": "750ml", "discount": "10% OFF" },
  { "id": "bv-2", "categoryId": "beverages", "name": "Red Bull Energy Drink", "price": 125, "originalPrice": 125, "image": "", "weight": "250ml", "discount": "" },
  { "id": "bv-3", "categoryId": "beverages", "name": "Bira 91 0.0 Alcohol-Free Beer", "price": 80, "originalPrice": 80, "image": "", "weight": "330ml", "discount": "" },
  { "id": "bv-4", "categoryId": "beverages", "name": "Paper Boat Sparkling Apple", "price": 60, "originalPrice": 60, "image": "", "weight": "600ml", "discount": "" },
  { "id": "bv-5", "categoryId": "beverages", "name": "Schweppes Ginger Ale", "price": 65, "originalPrice": 65, "image": "", "weight": "300ml", "discount": "" },
  { "id": "bv-6", "categoryId": "beverages", "name": "Nescafé Classic Instant Coffee", "price": 185, "originalPrice": 205, "image": "", "weight": "50g", "discount": "10% OFF" },
  { "id": "bv-7", "categoryId": "beverages", "name": "Tata Tea Gold", "price": 165, "originalPrice": 165, "image": "", "weight": "250g", "discount": "" },
  { "id": "bv-8", "categoryId": "beverages", "name": "Real Activ Mixed Fruit Juice", "price": 130, "originalPrice": 130, "image": "", "weight": "1L", "discount": "" },
  { "id": "bv-9", "categoryId": "beverages", "name": "Thums Up Soft Drink", "price": 70, "originalPrice": 70, "image": "", "weight": "1.25L", "discount": "" },
  { "id": "bv-10", "categoryId": "beverages", "name": "Diet Coke Can", "price": 40, "originalPrice": 40, "image": "", "weight": "300ml", "discount": "" },
  { "id": "bv-11", "categoryId": "beverages", "name": "Paper Boat Aam Panna", "price": 35, "originalPrice": 35, "image": "", "weight": "250ml", "discount": "" },
  { "id": "bv-12", "categoryId": "beverages", "name": "Raw Pressery Cold Pressed Guava Juice", "price": 80, "originalPrice": 80, "image": "", "weight": "250ml", "discount": "" },
  { "id": "bv-13", "categoryId": "beverages", "name": "Taj Mahal Tea", "price": 215, "originalPrice": 215, "image": "", "weight": "250g", "discount": "" },
  { "id": "bv-14", "categoryId": "beverages", "name": "Society Tea Leaf", "price": 175, "originalPrice": 175, "image": "", "weight": "250g", "discount": "" },
  { "id": "bv-15", "categoryId": "beverages", "name": "Chai Point Ginger Instant Tea", "price": 190, "originalPrice": 190, "image": "", "weight": "10 Sachets", "discount": "" },
  { "id": "bv-16", "categoryId": "beverages", "name": "Girnar Detox Green Tea Desi Kahwa", "price": 150, "originalPrice": 150, "image": "", "weight": "10 Bags", "discount": "" },
  { "id": "bv-17", "categoryId": "beverages", "name": "Wagh Bakri Masala Tea", "price": 160, "originalPrice": 160, "image": "", "weight": "250g", "discount": "" },
  { "id": "bv-18", "categoryId": "beverages", "name": "Raw Pressery Valencia Orange Juice", "price": 250, "originalPrice": 250, "image": "", "weight": "1L", "discount": "" },
  { "id": "bv-19", "categoryId": "beverages", "name": "Nescafé Gold Coffee", "price": 350, "originalPrice": 350, "image": "", "weight": "50g", "discount": "" },
  { "id": "bv-20", "categoryId": "beverages", "name": "Amul High Protein Lassi", "price": 45, "originalPrice": 45, "image": "", "weight": "250ml", "discount": "" },
  { "id": "bv-21", "categoryId": "beverages", "name": "Nescafé Ready-to-Drink Cold Coffee", "price": 45, "originalPrice": 45, "image": "", "weight": "180ml", "discount": "" },
  { "id": "bv-22", "categoryId": "beverages", "name": "Amul Kool Koko", "price": 30, "originalPrice": 30, "image": "", "weight": "200ml", "discount": "" },
  { "id": "bv-23", "categoryId": "beverages", "name": "Paper Boat Anardana", "price": 35, "originalPrice": 35, "image": "", "weight": "250ml", "discount": "" },
  { "id": "bv-24", "categoryId": "beverages", "name": "Raw Pressery Cold Pressed Coconut Water", "price": 65, "originalPrice": 65, "image": "", "weight": "200ml", "discount": "" },

  /* --- DAIRY (categoryId: dairy) --- */
  { "id": "dr-1", "categoryId": "dairy", "name": "Amul Taaza Toned Milk", "price": 29, "originalPrice": 29, "image": "", "weight": "500ml", "discount": "" },
  { "id": "dr-2", "categoryId": "dairy", "name": "Amul Salted Butter", "price": 58, "originalPrice": 62, "image": "", "weight": "100g", "discount": "6% OFF" },
  { "id": "dr-3", "categoryId": "dairy", "name": "Amul Masti Pouch Curd", "price": 35, "originalPrice": 35, "image": "", "weight": "400g", "discount": "" },
  { "id": "dr-4", "categoryId": "dairy", "name": "Milky Mist Paneer", "price": 115, "originalPrice": 115, "image": "", "weight": "200g", "discount": "" },
  { "id": "dr-5", "categoryId": "dairy", "name": "Epigamia Greek Yogurt Blueberry", "price": 65, "originalPrice": 65, "image": "", "weight": "90g", "discount": "" },
  { "id": "dr-6", "categoryId": "dairy", "name": "President Unsalted Butter", "price": 115, "originalPrice": 115, "image": "", "weight": "100g", "discount": "" },
  { "id": "dr-7", "categoryId": "dairy", "name": "Amul Processed Cheese Blocks", "price": 135, "originalPrice": 135, "image": "", "weight": "200g", "discount": "" },
  { "id": "dr-8", "categoryId": "dairy", "name": "Go Cheese Mozzarella Shredded", "price": 195, "originalPrice": 195, "image": "", "weight": "200g", "discount": "" },
  { "id": "dr-9", "categoryId": "dairy", "name": "Britannia Fresh Cream", "price": 75, "originalPrice": 75, "image": "", "weight": "250ml", "discount": "" },
  { "id": "dr-10", "categoryId": "dairy", "name": "Epigamia Greek Yogurt Natural", "price": 50, "originalPrice": 50, "image": "", "weight": "90g", "discount": "" },
  { "id": "dr-11", "categoryId": "dairy", "name": "Country Delight Low Fat Buffalo Milk", "price": 45, "originalPrice": 45, "image": "", "weight": "500ml", "discount": "" },
  { "id": "dr-12", "categoryId": "dairy", "name": "Amul Masti Spiced Buttermilk", "price": 15, "originalPrice": 15, "image": "", "weight": "200ml", "discount": "" },
  { "id": "dr-13", "categoryId": "dairy", "name": "Milky Mist Greek Yogurt Strawberry", "price": 60, "originalPrice": 60, "image": "", "weight": "90g", "discount": "" },
  { "id": "dr-14", "categoryId": "dairy", "name": "Amul Cheese Slices", "price": 160, "originalPrice": 160, "image": "", "weight": "200g", "discount": "" },
  { "id": "dr-15", "categoryId": "dairy", "name": "Amul Herb & Garlic Butter", "price": 65, "originalPrice": 65, "image": "", "weight": "100g", "discount": "" },
  { "id": "dr-16", "categoryId": "dairy", "name": "Milky Mist Paneer Tinned", "price": 260, "originalPrice": 260, "image": "", "weight": "500g", "discount": "" },
  { "id": "dr-17", "categoryId": "dairy", "name": "Go Cheese Mexican Shredded Cheese", "price": 225, "originalPrice": 225, "image": "", "weight": "200g", "discount": "" },
  { "id": "dr-18", "categoryId": "dairy", "name": "Amul Sour Cream", "price": 95, "originalPrice": 95, "image": "", "weight": "250g", "discount": "" },
  { "id": "dr-19", "categoryId": "dairy", "name": "Urban Platter Almond Milk", "price": 299, "originalPrice": 299, "image": "", "weight": "1L", "discount": "" },

  /* --- SWEETS & CHOCOLATES (categoryId: sweets_chocolates) --- */
  { "id": "sw-1", "categoryId": "sweets_chocolates", "name": "Ferrero Rocher T16", "price": 545, "originalPrice": 605, "image": "", "weight": "200g", "discount": "10% OFF" },
  { "id": "sw-2", "categoryId": "sweets_chocolates", "name": "Cadbury Celebrations Rich Cocoa", "price": 250, "originalPrice": 250, "image": "", "weight": "160g", "discount": "" },
  { "id": "sw-3", "categoryId": "sweets_chocolates", "name": "Hershey's Chocolate Syrup", "price": 240, "originalPrice": 240, "image": "", "weight": "623g", "discount": "" },
  { "id": "sw-4", "categoryId": "sweets_chocolates", "name": "Snickers Peanut Chocolate Bar", "price": 50, "originalPrice": 50, "image": "", "weight": "45g", "discount": "" },
  { "id": "sw-5", "categoryId": "sweets_chocolates", "name": "Cadbury Dairy Milk Silk Hazelnut", "price": 185, "originalPrice": 185, "image": "", "weight": "143g", "discount": "" },
  { "id": "sw-6", "categoryId": "sweets_chocolates", "name": "M&M's Chocolate Candies", "price": 110, "originalPrice": 110, "image": "", "weight": "45g", "discount": "" },
  { "id": "sw-7", "categoryId": "sweets_chocolates", "name": "Kinder Joy", "price": 50, "originalPrice": 50, "image": "", "weight": "2g", "discount": "" },
  { "id": "sw-8", "categoryId": "sweets_chocolates", "name": "Haldiram's Soan Papdi", "price": 110, "originalPrice": 110, "image": "", "weight": "250g", "discount": "" },
  { "id": "sw-9", "categoryId": "sweets_chocolates", "name": "Orion Choco Pie", "price": 150, "originalPrice": 150, "image": "", "weight": "Pack of 6", "discount": "" },
  { "id": "sw-10", "categoryId": "sweets_chocolates", "name": "Nutella Hazelnut Spread", "price": 375, "originalPrice": 375, "image": "", "weight": "350g", "discount": "" },
  { "id": "sw-11", "categoryId": "sweets_chocolates", "name": "Hershey's Strawberry Syrup", "price": 240, "originalPrice": 240, "image": "", "weight": "623g", "discount": "" },
  { "id": "sw-12", "categoryId": "sweets_chocolates", "name": "Amul Dark Chocolate Slab 55%", "price": 125, "originalPrice": 125, "image": "", "weight": "150g", "discount": "" },
  { "id": "sw-13", "categoryId": "sweets_chocolates", "name": "Urban Platter Semi-Sweet Choco Chips", "price": 325, "originalPrice": 325, "image": "", "weight": "200g", "discount": "" },
  { "id": "sw-14", "categoryId": "sweets_chocolates", "name": "Eagle Condensed Milk", "price": 75, "originalPrice": 75, "image": "", "weight": "200g", "discount": "" },
  { "id": "sw-15", "categoryId": "sweets_chocolates", "name": "Paper Boat Brownie Mix", "price": 199, "originalPrice": 199, "image": "", "weight": "300g", "discount": "" },
  { "id": "sw-16", "categoryId": "sweets_chocolates", "name": "MTR Gulab Jamun Mix", "price": 165, "originalPrice": 165, "image": "", "weight": "500g", "discount": "" },
  { "id": "sw-17", "categoryId": "sweets_chocolates", "name": "Haldiram's Gulab Jamun Tin", "price": 250, "originalPrice": 250, "image": "", "weight": "1kg", "discount": "" },
  { "id": "sw-18", "categoryId": "sweets_chocolates", "name": "Paper Boat Peanut Chikki", "price": 150, "originalPrice": 150, "image": "", "weight": "Jar of 15", "discount": "" },
  { "id": "sw-19", "categoryId": "sweets_chocolates", "name": "Cadbury 5 Star Chocolate Bar", "price": 20, "originalPrice": 20, "image": "", "weight": "40g", "discount": "" },
  { "id": "sw-20", "categoryId": "sweets_chocolates", "name": "Kwality Wall's Cornetto Double Chocolate", "price": 60, "originalPrice": 60, "image": "", "weight": "105ml", "discount": "" },
  { "id": "sw-21", "categoryId": "sweets_chocolates", "name": "Amul Epic Choco Almond Bar", "price": 50, "originalPrice": 50, "image": "", "weight": "80ml", "discount": "" },
  { "id": "sw-22", "categoryId": "sweets_chocolates", "name": "Hershey's Cocoa Powder", "price": 399, "originalPrice": 399, "image": "", "weight": "225g", "discount": "" },

  /* --- STAPLES & FLOURS (categoryId: staples_flours) --- */
  { "id": "st-1", "categoryId": "staples_flours", "name": "Daawat Rozana Gold Basmati Rice", "price": 115, "originalPrice": 115, "image": "", "weight": "1kg", "discount": "" },
  { "id": "st-2", "categoryId": "staples_flours", "name": "Aashirvaad Maida", "price": 75, "originalPrice": 75, "image": "", "weight": "1kg", "discount": "" },
  { "id": "st-3", "categoryId": "staples_flours", "name": "Urban Platter Quinoa", "price": 395, "originalPrice": 395, "image": "", "weight": "500g", "discount": "" },
  { "id": "st-4", "categoryId": "staples_flours", "name": "Aashirvaad Multigrain Atta", "price": 345, "originalPrice": 345, "image": "", "weight": "5kg", "discount": "" },
  { "id": "st-5", "categoryId": "staples_flours", "name": "Tata Sampann Moong Dal", "price": 115, "originalPrice": 115, "image": "", "weight": "500g", "discount": "" },
  { "id": "st-6", "categoryId": "staples_flours", "name": "Tata Sampann Toor Dal", "price": 185, "originalPrice": 185, "image": "", "weight": "1kg", "discount": "" },
  { "id": "st-7", "categoryId": "staples_flours", "name": "Aashirvaad Superior MP Atta", "price": 295, "originalPrice": 295, "image": "", "weight": "5kg", "discount": "" },

  /* --- BAKERY & BISCUITS (categoryId: bakery_biscuits) --- */
  { "id": "bk-1", "categoryId": "bakery_biscuits", "name": "English Oven Premium White Bread", "price": 50, "originalPrice": 50, "image": "", "weight": "400g", "discount": "" },
  { "id": "bk-2", "categoryId": "bakery_biscuits", "name": "Kellogg's Corn Flakes", "price": 210, "originalPrice": 210, "image": "", "weight": "475g", "discount": "" },
  { "id": "bk-3", "categoryId": "bakery_biscuits", "name": "iD Fresh Idli & Dosa Batter", "price": 90, "originalPrice": 90, "image": "", "weight": "1kg", "discount": "" },
  { "id": "bk-4", "categoryId": "bakery_biscuits", "name": "Quaker Oats", "price": 199, "originalPrice": 199, "image": "", "weight": "1kg", "discount": "" },
  { "id": "bk-5", "categoryId": "bakery_biscuits", "name": "MTR Rava Idli Mix", "price": 135, "originalPrice": 135, "image": "", "weight": "500g", "discount": "" },
  { "id": "bk-6", "categoryId": "bakery_biscuits", "name": "Saffola Masala Oats Peppy Tomato", "price": 20, "originalPrice": 20, "image": "", "weight": "38g", "discount": "" },
  { "id": "bk-7", "categoryId": "bakery_biscuits", "name": "Baggry's Muesli - Fruit and Nut", "price": 325, "originalPrice": 325, "image": "", "weight": "400g", "discount": "" },
  { "id": "bk-8", "categoryId": "bakery_biscuits", "name": "Parle-G Gold Biscuits", "price": 135, "originalPrice": 135, "image": "", "weight": "1kg", "discount": "" },
  { "id": "bk-9", "categoryId": "bakery_biscuits", "name": "Britannia Good Day Cashew Cookies", "price": 40, "originalPrice": 40, "image": "", "weight": "200g", "discount": "" },
  { "id": "bk-10", "categoryId": "bakery_biscuits", "name": "Hide & Seek Chocolate Chip Cookies", "price": 35, "originalPrice": 35, "image": "", "weight": "120g", "discount": "" },
  { "id": "bk-11", "categoryId": "bakery_biscuits", "name": "McVitie's Digestive Biscuits", "price": 85, "originalPrice": 85, "image": "", "weight": "250g", "discount": "" },
  { "id": "bk-12", "categoryId": "bakery_biscuits", "name": "Milk Bikis Milk Biscuits", "price": 35, "originalPrice": 35, "image": "", "weight": "200g", "discount": "" },
  { "id": "bk-13", "categoryId": "bakery_biscuits", "name": "Sunfeast Dark Fantasy Choco Fills", "price": 45, "originalPrice": 45, "image": "", "weight": "75g", "discount": "" },
  { "id": "bk-14", "categoryId": "bakery_biscuits", "name": "Supertasty Suji Rusk", "price": 80, "originalPrice": 80, "image": "", "weight": "400g", "discount": "" },
  { "id": "bk-15", "categoryId": "bakery_biscuits", "name": "Betty Crocker Pancake Mix", "price": 299, "originalPrice": 299, "image": "", "weight": "500g", "discount": "" },
  { "id": "bk-16", "categoryId": "bakery_biscuits", "name": "Pillsbury Choco Chip Pancake Mix", "price": 165, "originalPrice": 165, "image": "", "weight": "250g", "discount": "" },
  { "id": "bk-17", "categoryId": "bakery_biscuits", "name": "Sunfeast Marie Light Biscuits", "price": 35, "originalPrice": 35, "image": "", "weight": "200g", "discount": "" },
  { "id": "bk-18", "categoryId": "bakery_biscuits", "name": "True Elements Rolled Oats", "price": 345, "originalPrice": 345, "image": "", "weight": "1kg", "discount": "" },
  { "id": "bk-19", "categoryId": "bakery_biscuits", "name": "Nature Valley Oats & Honey Granola Bar", "price": 60, "originalPrice": 60, "image": "", "weight": "42g", "discount": "" },
  { "id": "bk-20", "categoryId": "bakery_biscuits", "name": "iD Fresh Malabar Paratha", "price": 110, "originalPrice": 110, "image": "", "weight": "Pack of 5", "discount": "" },
  { "id": "bk-21", "categoryId": "bakery_biscuits", "name": "Sunfeast Mom's Magic Cashew & Almond", "price": 40, "originalPrice": 40, "image": "", "weight": "200g", "discount": "" },
  { "id": "bk-22", "categoryId": "bakery_biscuits", "name": "Britannia Jim Jam Sandwich Biscuits", "price": 35, "originalPrice": 35, "image": "", "weight": "150g", "discount": "" },
  { "id": "bk-23", "categoryId": "bakery_biscuits", "name": "The Baker's Dozen Sourdough Bread", "price": 120, "originalPrice": 120, "image": "", "weight": "400g", "discount": "" },
  { "id": "bk-24", "categoryId": "bakery_biscuits", "name": "English Oven Whole Wheat Sandwich Bread", "price": 55, "originalPrice": 55, "image": "", "weight": "400g", "discount": "" },
  { "id": "bk-25", "categoryId": "bakery_biscuits", "name": "Yoga Bar Rolled Oats", "price": 199, "originalPrice": 199, "image": "", "weight": "500g", "discount": "" },

  /* --- PANTRY, SPICES & SAUCES (categoryId: pantry_spices_sauces) --- */
  { "id": "pn-1", "categoryId": "pantry_spices_sauces", "name": "Everest Shahi Biryani Masala", "price": 78, "originalPrice": 78, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-2", "categoryId": "pantry_spices_sauces", "name": "Dabur Hommade Ginger Garlic Paste", "price": 55, "originalPrice": 55, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-3", "categoryId": "pantry_spices_sauces", "name": "Saffola Gold Cooking Oil", "price": 165, "originalPrice": 165, "image": "", "weight": "1L", "discount": "" },
  { "id": "pn-4", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Saffron Threads", "price": 350, "originalPrice": 350, "image": "", "weight": "1g", "discount": "" },
  { "id": "pn-5", "categoryId": "pantry_spices_sauces", "name": "Keya Whole Cinnamon Sticks", "price": 90, "originalPrice": 90, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-6", "categoryId": "pantry_spices_sauces", "name": "Catch Green Cardamom", "price": 210, "originalPrice": 210, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-7", "categoryId": "pantry_spices_sauces", "name": "Kissan Mixed Fruit Jam", "price": 85, "originalPrice": 85, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-8", "categoryId": "pantry_spices_sauces", "name": "Dabur Honey", "price": 120, "originalPrice": 120, "image": "", "weight": "250g", "discount": "" },
  { "id": "pn-9", "categoryId": "pantry_spices_sauces", "name": "Wingreens Farms Maple Syrup", "price": 450, "originalPrice": 450, "image": "", "weight": "340g", "discount": "" },
  { "id": "pn-10", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Organic Honey", "price": 450, "originalPrice": 450, "image": "", "weight": "500g", "discount": "" },
  { "id": "pn-11", "categoryId": "pantry_spices_sauces", "name": "Sprig Vanilla Extract", "price": 599, "originalPrice": 599, "image": "", "weight": "50ml", "discount": "" },
  { "id": "pn-12", "categoryId": "pantry_spices_sauces", "name": "Borges Extra Virgin Olive Oil", "price": 850, "originalPrice": 850, "image": "", "weight": "500ml", "discount": "" },
  { "id": "pn-13", "categoryId": "pantry_spices_sauces", "name": "Dr. Oetker FunFoods Pasta & Pizza Sauce", "price": 125, "originalPrice": 125, "image": "", "weight": "325g", "discount": "" },
  { "id": "pn-14", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Dried Oregano", "price": 150, "originalPrice": 150, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-15", "categoryId": "pantry_spices_sauces", "name": "Snaith Dried Basil", "price": 110, "originalPrice": 110, "image": "", "weight": "30g", "discount": "" },
  { "id": "pn-16", "categoryId": "pantry_spices_sauces", "name": "Keya Red Chili Flakes", "price": 95, "originalPrice": 95, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-17", "categoryId": "pantry_spices_sauces", "name": "Vego Canned Olives Sliced Black", "price": 225, "originalPrice": 225, "image": "", "weight": "450g", "discount": "" },
  { "id": "pn-18", "categoryId": "pantry_spices_sauces", "name": "Trust Pure White Sugar", "price": 55, "originalPrice": 55, "image": "", "weight": "1kg", "discount": "" },
  { "id": "pn-19", "categoryId": "pantry_spices_sauces", "name": "Weikfield Baking Powder", "price": 45, "originalPrice": 45, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-20", "categoryId": "pantry_spices_sauces", "name": "Blue Bird Cocoa Powder", "price": 95, "originalPrice": 95, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-21", "categoryId": "pantry_spices_sauces", "name": "Purix Corn Flour", "price": 60, "originalPrice": 60, "image": "", "weight": "500g", "discount": "" },
  { "id": "pn-22", "categoryId": "pantry_spices_sauces", "name": "Foster Clark's Vanilla Essence", "price": 85, "originalPrice": 85, "image": "", "weight": "28ml", "discount": "" },
  { "id": "pn-23", "categoryId": "pantry_spices_sauces", "name": "Hellmann's Real Mayonnaise (Eggless)", "price": 149, "originalPrice": 149, "image": "", "weight": "250g", "discount": "" },
  { "id": "pn-24", "categoryId": "pantry_spices_sauces", "name": "Del Monte Apple Cider Vinegar", "price": 350, "originalPrice": 350, "image": "", "weight": "500ml", "discount": "" },
  { "id": "pn-25", "categoryId": "pantry_spices_sauces", "name": "Disano Extra Light Olive Oil", "price": 999, "originalPrice": 999, "image": "", "weight": "1L", "discount": "" },
  { "id": "pn-26", "categoryId": "pantry_spices_sauces", "name": "Saffola Honey", "price": 110, "originalPrice": 110, "image": "", "weight": "250g", "discount": "" },
  { "id": "pn-27", "categoryId": "pantry_spices_sauces", "name": "Zoff Himalayan Pink Salt", "price": 65, "originalPrice": 65, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-28", "categoryId": "pantry_spices_sauces", "name": "Nando's Peri Peri Sauce - Lemon & Herb", "price": 345, "originalPrice": 345, "image": "", "weight": "125g", "discount": "" },
  { "id": "pn-29", "categoryId": "pantry_spices_sauces", "name": "Yoga Bar Peanut Butter - Crunchy", "price": 249, "originalPrice": 249, "image": "", "weight": "400g", "discount": "" },
  { "id": "pn-30", "categoryId": "pantry_spices_sauces", "name": "Pintola Organic Peanut Butter", "price": 299, "originalPrice": 299, "image": "", "weight": "350g", "discount": "" },
  { "id": "pn-31", "categoryId": "pantry_spices_sauces", "name": "Veeba Burger Mayonnaise", "price": 110, "originalPrice": 110, "image": "", "weight": "250g", "discount": "" },
  { "id": "pn-32", "categoryId": "pantry_spices_sauces", "name": "Wingreens Farms Peri Peri Mayo", "price": 149, "originalPrice": 149, "image": "", "weight": "180g", "discount": "" },
  { "id": "pn-33", "categoryId": "pantry_spices_sauces", "name": "Kissan Fresh Tomato Ketchup", "price": 145, "originalPrice": 145, "image": "", "weight": "950g", "discount": "" },
  { "id": "pn-34", "categoryId": "pantry_spices_sauces", "name": "Sana Black Olives Sliced", "price": 165, "originalPrice": 165, "image": "", "weight": "180g", "discount": "" },
  { "id": "pn-35", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Jalapeno Slices", "price": 225, "originalPrice": 225, "image": "", "weight": "350g", "discount": "" },
  { "id": "pn-36", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Barbeque Seasoning", "price": 250, "originalPrice": 250, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-37", "categoryId": "pantry_spices_sauces", "name": "Veeba Tandoori Dressing", "price": 149, "originalPrice": 149, "image": "", "weight": "300g", "discount": "" },
  { "id": "pn-38", "categoryId": "pantry_spices_sauces", "name": "Keya Black Pepper Grinder", "price": 215, "originalPrice": 215, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-39", "categoryId": "pantry_spices_sauces", "name": "Sprig Smoked Paprika", "price": 399, "originalPrice": 399, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-40", "categoryId": "pantry_spices_sauces", "name": "Del Monte Roasted Garlic Mayo", "price": 110, "originalPrice": 110, "image": "", "weight": "250g", "discount": "" },
  { "id": "pn-41", "categoryId": "pantry_spices_sauces", "name": "Urban Platter Refried Beans", "price": 275, "originalPrice": 275, "image": "", "weight": "400g", "discount": "" },
  { "id": "pn-42", "categoryId": "pantry_spices_sauces", "name": "Veeba Salsa Mexican", "price": 115, "originalPrice": 115, "image": "", "weight": "325g", "discount": "" },
  { "id": "pn-43", "categoryId": "pantry_spices_sauces", "name": "Keya Mexican Seasoning", "price": 95, "originalPrice": 95, "image": "", "weight": "50g", "discount": "" },
  { "id": "pn-44", "categoryId": "pantry_spices_sauces", "name": "Cornitos Sliced Jalapenos", "price": 175, "originalPrice": 175, "image": "", "weight": "340g", "discount": "" },
  { "id": "pn-45", "categoryId": "pantry_spices_sauces", "name": "Veeba Chipotle Southwest Dressing", "price": 149, "originalPrice": 149, "image": "", "weight": "300g", "discount": "" },
  { "id": "pn-46", "categoryId": "pantry_spices_sauces", "name": "Ching's Secret Red Chilli Sauce", "price": 55, "originalPrice": 55, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-47", "categoryId": "pantry_spices_sauces", "name": "Tata Sampann Turmeric Powder", "price": 65, "originalPrice": 65, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-48", "categoryId": "pantry_spices_sauces", "name": "Everest Tikhalal Red Chilli Powder", "price": 75, "originalPrice": 75, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-49", "categoryId": "pantry_spices_sauces", "name": "MDH Kitchen King Masala", "price": 88, "originalPrice": 88, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-50", "categoryId": "pantry_spices_sauces", "name": "Everest Garam Masala", "price": 95, "originalPrice": 95, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-51", "categoryId": "pantry_spices_sauces", "name": "Catch Coriander Powder", "price": 85, "originalPrice": 85, "image": "", "weight": "200g", "discount": "" },
  { "id": "pn-52", "categoryId": "pantry_spices_sauces", "name": "Dabur Hommade Tomato Purée", "price": 35, "originalPrice": 35, "image": "", "weight": "200ml", "discount": "" },
  { "id": "pn-53", "categoryId": "pantry_spices_sauces", "name": "Fortune Soyabean Oil", "price": 145, "originalPrice": 145, "image": "", "weight": "1L", "discount": "" },
  { "id": "pn-54", "categoryId": "pantry_spices_sauces", "name": "Organic Tattva Cumin Seeds (Jeera)", "price": 110, "originalPrice": 110, "image": "", "weight": "100g", "discount": "" },
  { "id": "pn-55", "categoryId": "pantry_spices_sauces", "name": "Mother's Recipe Mixed Pickle", "price": 110, "originalPrice": 110, "image": "", "weight": "400g", "discount": "" },
  { "id": "pn-56", "categoryId": "pantry_spices_sauces", "name": "Honey & Dough Natural Peanut Butter", "price": 275, "originalPrice": 275, "image": "", "weight": "300g", "discount": "" },
  { "id": "pn-57", "categoryId": "pantry_spices_sauces", "name": "Saffola Honey with Ashwagandha", "price": 145, "originalPrice": 145, "image": "", "weight": "250g", "discount": "" },

  /* --- FRESH PRODUCE (categoryId: fresh_produce) --- */
  { "id": "fp-1", "categoryId": "fresh_produce", "name": "Fresho Brown Onion", "price": 45, "originalPrice": 45, "image": "", "weight": "200g", "discount": "" },
  { "id": "fp-2", "categoryId": "fresh_produce", "name": "Loose Mint Leaves", "price": 15, "originalPrice": 15, "image": "", "weight": "1 Bunch", "discount": "" },
  { "id": "fp-3", "categoryId": "fresh_produce", "name": "Coriander Leaves", "price": 15, "originalPrice": 15, "image": "", "weight": "1 Bunch", "discount": "" },
  { "id": "fp-4", "categoryId": "fresh_produce", "name": "Driscoll's Fresh Strawberries", "price": 350, "originalPrice": 350, "image": "", "weight": "200g", "discount": "" },
  { "id": "fp-5", "categoryId": "fresh_produce", "name": "Fresho Cherry Tomatoes", "price": 60, "originalPrice": 60, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-6", "categoryId": "fresh_produce", "name": "Fresho Iceberg Lettuce", "price": 90, "originalPrice": 90, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-7", "categoryId": "fresh_produce", "name": "Fresho English Cucumber", "price": 45, "originalPrice": 45, "image": "", "weight": "500g", "discount": "" },
  { "id": "fp-8", "categoryId": "fresh_produce", "name": "Fresho Red/Yellow Bell Peppers", "price": 110, "originalPrice": 110, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-9", "categoryId": "fresh_produce", "name": "Fresho Sweet Corn", "price": 55, "originalPrice": 55, "image": "", "weight": "Pack of 2", "discount": "" },
  { "id": "fp-10", "categoryId": "fresh_produce", "name": "Fresho Baby Spinach", "price": 35, "originalPrice": 35, "image": "", "weight": "100g", "discount": "" },
  { "id": "fp-11", "categoryId": "fresh_produce", "name": "Zespri Kiwi Fruit", "price": 180, "originalPrice": 180, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "fp-12", "categoryId": "fresh_produce", "name": "Fresho Robusta Banana", "price": 35, "originalPrice": 35, "image": "", "weight": "500g", "discount": "" },
  { "id": "fp-13", "categoryId": "fresh_produce", "name": "Fresho Pomegranate Seeds", "price": 140, "originalPrice": 140, "image": "", "weight": "200g", "discount": "" },
  { "id": "fp-14", "categoryId": "fresh_produce", "name": "Fresho Button Mushroom", "price": 65, "originalPrice": 65, "image": "", "weight": "200g", "discount": "" },
  { "id": "fp-15", "categoryId": "fresh_produce", "name": "Fresho Red Onion", "price": 30, "originalPrice": 30, "image": "", "weight": "500g", "discount": "" },
  { "id": "fp-16", "categoryId": "fresh_produce", "name": "Fresho Green Capsicum", "price": 25, "originalPrice": 25, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-17", "categoryId": "fresh_produce", "name": "Fresho Avocado - Imported", "price": 250, "originalPrice": 250, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "fp-18", "categoryId": "fresh_produce", "name": "Fresho Lemon", "price": 40, "originalPrice": 40, "image": "", "weight": "Pack of 4", "discount": "" },
  { "id": "fp-19", "categoryId": "fresh_produce", "name": "Fresho Garlic", "price": 85, "originalPrice": 85, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-20", "categoryId": "fresh_produce", "name": "Fresho Ginger", "price": 40, "originalPrice": 40, "image": "", "weight": "250g", "discount": "" },
  { "id": "fp-21", "categoryId": "fresh_produce", "name": "Fresho Hybrid Tomato", "price": 40, "originalPrice": 40, "image": "", "weight": "500g", "discount": "" },
  { "id": "fp-22", "categoryId": "fresh_produce", "name": "Fresho Blueberry - Imported", "price": 450, "originalPrice": 450, "image": "", "weight": "125g", "discount": "" },

  /* --- MEAT & EGGS (categoryId: meat_eggs) --- */
  { "id": "mt-1", "categoryId": "meat_eggs", "name": "Licious Chicken Biryani Cut", "price": 245, "originalPrice": 245, "image": "", "weight": "500g", "discount": "" },
  { "id": "mt-2", "categoryId": "meat_eggs", "name": "Eggoz White Eggs", "price": 55, "originalPrice": 55, "image": "", "weight": "Pack of 6", "discount": "" },
  { "id": "mt-3", "categoryId": "meat_eggs", "name": "Zorabian Chicken Salami - Smoked", "price": 245, "originalPrice": 245, "image": "", "weight": "250g", "discount": "" },
  { "id": "mt-4", "categoryId": "meat_eggs", "name": "Prasuma Chicken Smoked Ham", "price": 295, "originalPrice": 295, "image": "", "weight": "200g", "discount": "" },
  { "id": "mt-5", "categoryId": "meat_eggs", "name": "Licious Peppery Chicken Salami", "price": 225, "originalPrice": 225, "image": "", "weight": "250g", "discount": "" },
  { "id": "mt-6", "categoryId": "meat_eggs", "name": "Zorabian Marinated Chicken Tikka", "price": 260, "originalPrice": 260, "image": "", "weight": "250g", "discount": "" },
  { "id": "mt-7", "categoryId": "meat_eggs", "name": "Prasuma Pork Sausages - BBQ", "price": 345, "originalPrice": 345, "image": "", "weight": "250g", "discount": "" },
  { "id": "mt-8", "categoryId": "meat_eggs", "name": "ITC Master Chef Chicken Galouti Kebab", "price": 195, "originalPrice": 195, "image": "", "weight": "200g", "discount": "" },

  /* --- HEALTH & WELLNESS (categoryId: health_wellness) --- */
  { "id": "hl-1", "categoryId": "health_wellness", "name": "Vicks VapoRub", "price": 105, "originalPrice": 105, "image": "", "weight": "25g", "discount": "" },
  { "id": "hl-2", "categoryId": "health_wellness", "name": "Dettol Antiseptic Liquid", "price": 145, "originalPrice": 155, "image": "", "weight": "250ml", "discount": "6% OFF" },
  { "id": "hl-3", "categoryId": "health_wellness", "name": "Himalaya Tulsi Syrup", "price": 110, "originalPrice": 110, "image": "", "weight": "100ml", "discount": "" },
  { "id": "hl-4", "categoryId": "health_wellness", "name": "Paracetamol 500mg", "price": 25, "originalPrice": 25, "image": "", "weight": "Strip of 10", "discount": "" },
  { "id": "hl-5", "categoryId": "health_wellness", "name": "Breathe Easy Eucalyptus Oil", "price": 195, "originalPrice": 195, "image": "", "weight": "15ml", "discount": "" },
  { "id": "hl-6", "categoryId": "health_wellness", "name": "Horlicks Mother's Plus", "price": 550, "originalPrice": 550, "image": "", "weight": "500g", "discount": "" },
  { "id": "hl-7", "categoryId": "health_wellness", "name": "Cadbury Bournvita Health Drink", "price": 235, "originalPrice": 235, "image": "", "weight": "500g Jar", "discount": "" },
  { "id": "hl-8", "categoryId": "health_wellness", "name": "Patanjali Giloy Juice", "price": 105, "originalPrice": 105, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hl-9", "categoryId": "health_wellness", "name": "Dr. Morepen Digital Thermometer", "price": 249, "originalPrice": 249, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "hl-10", "categoryId": "health_wellness", "name": "MuscleBlaze Whey Protein 80% Raw", "price": 2200, "originalPrice": 2200, "image": "", "weight": "1kg", "discount": "" },
  { "id": "hl-11", "categoryId": "health_wellness", "name": "Fast&Up Reload Hydration - Orange", "price": 320, "originalPrice": 320, "image": "", "weight": "20 Tabs", "discount": "" },
  { "id": "hl-12", "categoryId": "health_wellness", "name": "RiteBite Max Protein Daily Choco Berry Bar", "price": 75, "originalPrice": 75, "image": "", "weight": "50g", "discount": "" },
  { "id": "hl-13", "categoryId": "health_wellness", "name": "Protinex Nutrition Health Drink", "price": 625, "originalPrice": 625, "image": "", "weight": "400g Jar", "discount": "" },
  { "id": "hl-14", "categoryId": "health_wellness", "name": "Raw Pressery Protein Shake - Chocolate", "price": 120, "originalPrice": 120, "image": "", "weight": "200ml", "discount": "" },
  { "id": "hl-15", "categoryId": "health_wellness", "name": "Fast&Up Whey Protein Isolate", "price": 110, "originalPrice": 110, "image": "", "weight": "30g Sachet", "discount": "" },

  /* --- HOME & CLEANING (categoryId: home_cleaning) --- */
  { "id": "hc-1", "categoryId": "home_cleaning", "name": "Lizol Disinfectant Floor Cleaner Citrus", "price": 115, "originalPrice": 115, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-2", "categoryId": "home_cleaning", "name": "Harpic Power Plus Toilet Cleaner", "price": 105, "originalPrice": 105, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-3", "categoryId": "home_cleaning", "name": "Colin Glass and Surface Cleaner", "price": 105, "originalPrice": 105, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-4", "categoryId": "home_cleaning", "name": "Vim Lemon Dishwash Liquid", "price": 115, "originalPrice": 115, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-5", "categoryId": "home_cleaning", "name": "Scotch-Brite Kitchen Scrub Pad", "price": 75, "originalPrice": 75, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "hc-6", "categoryId": "home_cleaning", "name": "Godrej aer Pocket Bathroom Fragrance", "price": 165, "originalPrice": 165, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "hc-7", "categoryId": "home_cleaning", "name": "Domex Disinfectant Floor Cleaner", "price": 199, "originalPrice": 199, "image": "", "weight": "1L", "discount": "" },
  { "id": "hc-8", "categoryId": "home_cleaning", "name": "Pril Degreasing Dishwash Liquid", "price": 105, "originalPrice": 105, "image": "", "weight": "425ml", "discount": "" },
  { "id": "hc-9", "categoryId": "home_cleaning", "name": "Exo Dishwash Bar", "price": 60, "originalPrice": 60, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "hc-10", "categoryId": "home_cleaning", "name": "Gala Dustpan with Brush", "price": 149, "originalPrice": 149, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "hc-11", "categoryId": "home_cleaning", "name": "Odonil Air Freshener Blocks", "price": 185, "originalPrice": 185, "image": "", "weight": "Pack of 4", "discount": "" },
  { "id": "hc-12", "categoryId": "home_cleaning", "name": "Sani Fresh Shine Toilet Cleaner", "price": 95, "originalPrice": 95, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-13", "categoryId": "home_cleaning", "name": "Hit Flying Insect Killer Spray", "price": 345, "originalPrice": 345, "image": "", "weight": "625ml", "discount": "" },
  { "id": "hc-14", "categoryId": "home_cleaning", "name": "Eveready Alkaline Batteries AA", "price": 350, "originalPrice": 350, "image": "", "weight": "Pack of 10", "discount": "" },
  { "id": "hc-15", "categoryId": "home_cleaning", "name": "Solo Aluminum Foil", "price": 240, "originalPrice": 240, "image": "", "weight": "72 meters", "discount": "" },
  { "id": "hc-16", "categoryId": "home_cleaning", "name": "Surf Excel Matic Top Load Liquid Detergent", "price": 240, "originalPrice": 240, "image": "", "weight": "1L", "discount": "" },
  { "id": "hc-17", "categoryId": "home_cleaning", "name": "Ariel Matic Front Load Washing Powder", "price": 265, "originalPrice": 265, "image": "", "weight": "1kg", "discount": "" },
  { "id": "hc-18", "categoryId": "home_cleaning", "name": "Comfort Fabric Conditioner Morning Fresh", "price": 225, "originalPrice": 225, "image": "", "weight": "800ml", "discount": "" },
  { "id": "hc-19", "categoryId": "home_cleaning", "name": "Rin Advanced Detergent Bar", "price": 65, "originalPrice": 65, "image": "", "weight": "Pack of 4", "discount": "" },
  { "id": "hc-20", "categoryId": "home_cleaning", "name": "Vanish Oxi Action Fabric Stain Remover", "price": 199, "originalPrice": 199, "image": "", "weight": "400ml", "discount": "" },
  { "id": "hc-21", "categoryId": "home_cleaning", "name": "Ezee Liquid Detergent for Winterwear", "price": 210, "originalPrice": 210, "image": "", "weight": "1L", "discount": "" },
  { "id": "hc-22", "categoryId": "home_cleaning", "name": "Ujala Supreme Fabric Whitener", "price": 20, "originalPrice": 20, "image": "", "weight": "75ml", "discount": "" },
  { "id": "hc-23", "categoryId": "home_cleaning", "name": "Tide Plus Extra Power Detergent Powder", "price": 145, "originalPrice": 145, "image": "", "weight": "1kg", "discount": "" },
  { "id": "hc-24", "categoryId": "home_cleaning", "name": "Gala Plastic Cloth Clips", "price": 85, "originalPrice": 85, "image": "", "weight": "Pack of 12", "discount": "" },
  { "id": "hc-25", "categoryId": "home_cleaning", "name": "Dettol Laundry Sanitizer", "price": 249, "originalPrice": 249, "image": "", "weight": "480ml", "discount": "" },
  { "id": "hc-26", "categoryId": "home_cleaning", "name": "Comfort Fabric Conditioner After Wash", "price": 60, "originalPrice": 60, "image": "", "weight": "200ml", "discount": "" },
  { "id": "hc-27", "categoryId": "home_cleaning", "name": "Revive Liquid Starch", "price": 65, "originalPrice": 65, "image": "", "weight": "200ml", "discount": "" },
  { "id": "hc-28", "categoryId": "home_cleaning", "name": "Godrej Genteel Liquid Detergent", "price": 185, "originalPrice": 185, "image": "", "weight": "1L", "discount": "" },
  { "id": "hc-29", "categoryId": "home_cleaning", "name": "SafeWash Liquid Detergent", "price": 120, "originalPrice": 120, "image": "", "weight": "500ml", "discount": "" },
  { "id": "hc-30", "categoryId": "home_cleaning", "name": "Gala Ironing Board Cover", "price": 299, "originalPrice": 299, "image": "", "weight": "1 Unit", "discount": "" },

  /* --- PERSONAL CARE & HYGIENE (categoryId: personal_hygiene) --- */
  { "id": "ph-1", "categoryId": "personal_hygiene", "name": "Dettol Liquid Handwash Pump Original", "price": 135, "originalPrice": 135, "image": "", "weight": "250ml", "discount": "" },
  { "id": "ph-2", "categoryId": "personal_hygiene", "name": "Savlon Hand Sanitizer", "price": 250, "originalPrice": 250, "image": "", "weight": "500ml", "discount": "" },
  { "id": "ph-3", "categoryId": "personal_hygiene", "name": "Lifebuoy Total 10 Soap", "price": 160, "originalPrice": 160, "image": "", "weight": "Pack of 4", "discount": "" },
  { "id": "ph-4", "categoryId": "personal_hygiene", "name": "Pears Pure & Gentle Soap", "price": 225, "originalPrice": 225, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "ph-5", "categoryId": "personal_hygiene", "name": "Colgate MaxFresh Toothpaste", "price": 115, "originalPrice": 115, "image": "", "weight": "150g", "discount": "" },
  { "id": "ph-6", "categoryId": "personal_hygiene", "name": "Listerine Mouthwash Cool Mint", "price": 165, "originalPrice": 165, "image": "", "weight": "250ml", "discount": "" },
  { "id": "ph-7", "categoryId": "personal_hygiene", "name": "Whisper Choice Ultra Sanitary Pads", "price": 185, "originalPrice": 185, "image": "", "weight": "Pack of 20", "discount": "" },
  { "id": "ph-8", "categoryId": "personal_hygiene", "name": "Stayfree Secure Cottony Soft", "price": 299, "originalPrice": 299, "image": "", "weight": "Pack of 40", "discount": "" },
  { "id": "ph-9", "categoryId": "personal_hygiene", "name": "Gillette Mach3 Men's Razor", "price": 450, "originalPrice": 450, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "ph-10", "categoryId": "personal_hygiene", "name": "Oral-B Soft Toothbrush", "price": 150, "originalPrice": 150, "image": "", "weight": "Pack of 3", "discount": "" },
  { "id": "ph-11", "categoryId": "personal_hygiene", "name": "Park Avenue Good Morning Deodorant", "price": 210, "originalPrice": 210, "image": "", "weight": "150ml", "discount": "" },
  { "id": "ph-12", "categoryId": "personal_hygiene", "name": "Nivea Soft Moisturizing Cream", "price": 199, "originalPrice": 199, "image": "", "weight": "100ml", "discount": "" },
  { "id": "ph-13", "categoryId": "personal_hygiene", "name": "Clean & Clear Foaming Face Wash", "price": 185, "originalPrice": 185, "image": "", "weight": "100ml", "discount": "" },
  { "id": "ph-14", "categoryId": "personal_hygiene", "name": "Dettol Multi-Surface Disinfectant Spray", "price": 199, "originalPrice": 199, "image": "", "weight": "225ml", "discount": "" },
  { "id": "ph-15", "categoryId": "personal_hygiene", "name": "Origami Face Tissues", "price": 110, "originalPrice": 110, "image": "", "weight": "Pack of 200", "discount": "" },
  { "id": "ph-16", "categoryId": "personal_hygiene", "name": "Softouch Tissues", "price": 85, "originalPrice": 85, "image": "", "weight": "Pack of 100", "discount": "" },
  { "id": "ph-17", "categoryId": "personal_hygiene", "name": "Dettol Liquid Handwash Refill", "price": 209, "originalPrice": 209, "image": "", "weight": "1.5L", "discount": "" },

  /* --- HAIR CARE (categoryId: hair_care) --- */
  { "id": "hr-1", "categoryId": "hair_care", "name": "L'Oréal Paris Total Repair 5 Shampoo", "price": 649, "originalPrice": 649, "image": "", "weight": "640ml", "discount": "" },
  { "id": "hr-2", "categoryId": "hair_care", "name": "Tresemmé Keratin Smooth Conditioner", "price": 240, "originalPrice": 240, "image": "", "weight": "190ml", "discount": "" },
  { "id": "hr-3", "categoryId": "hair_care", "name": "Parachute Advansed Coconut Hair Oil", "price": 115, "originalPrice": 115, "image": "", "weight": "200ml", "discount": "" },
  { "id": "hr-4", "categoryId": "hair_care", "name": "Indulekha Bringha Hair Oil", "price": 430, "originalPrice": 430, "image": "", "weight": "100ml", "discount": "" },
  { "id": "hr-5", "categoryId": "hair_care", "name": "Livon Hair Serum for Women", "price": 300, "originalPrice": 300, "image": "", "weight": "100ml", "discount": "" },
  { "id": "hr-6", "categoryId": "hair_care", "name": "Head & Shoulders Anti-Dandruff Shampoo", "price": 195, "originalPrice": 195, "image": "", "weight": "180ml", "discount": "" },
  { "id": "hr-7", "categoryId": "hair_care", "name": "Dove Intense Repair Hair Mask", "price": 550, "originalPrice": 550, "image": "", "weight": "200ml", "discount": "" },
  { "id": "hr-8", "categoryId": "hair_care", "name": "Mamaearth Onion Hair Fall Control Oil", "price": 399, "originalPrice": 399, "image": "", "weight": "150ml", "discount": "" },
  { "id": "hr-9", "categoryId": "hair_care", "name": "Biotique Bio Kelp Protein Shampoo", "price": 165, "originalPrice": 165, "image": "", "weight": "190ml", "discount": "" },
  { "id": "hr-10", "categoryId": "hair_care", "name": "Pantene Advanced Hair Fall Solution Shampoo", "price": 180, "originalPrice": 180, "image": "", "weight": "180ml", "discount": "" },
  { "id": "hr-11", "categoryId": "hair_care", "name": "Godrej Expert Rich Crème Hair Colour - Black", "price": 35, "originalPrice": 35, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "hr-12", "categoryId": "hair_care", "name": "Enliven Ultra Hold Hair Gel", "price": 199, "originalPrice": 199, "image": "", "weight": "250ml", "discount": "" },
  { "id": "hr-13", "categoryId": "hair_care", "name": "Garnier Fructis Long & Strong Shampoo", "price": 150, "originalPrice": 150, "image": "", "weight": "175ml", "discount": "" },
  { "id": "hr-14", "categoryId": "hair_care", "name": "Beardo Hair Wax for Men - Strong Hold", "price": 299, "originalPrice": 299, "image": "", "weight": "50g", "discount": "" },
  { "id": "hr-15", "categoryId": "hair_care", "name": "Set Wet Vertical Hold Hair Gel", "price": 110, "originalPrice": 110, "image": "", "weight": "100ml", "discount": "" },

  /* --- BABY CARE (categoryId: baby_care) --- */
  { "id": "bb-1", "categoryId": "baby_care", "name": "Pampers All Round Protection Pants - L", "price": 1149, "originalPrice": 1149, "image": "", "weight": "Pack of 64", "discount": "" },
  { "id": "bb-2", "categoryId": "baby_care", "name": "Huggies Wonder Pants - M", "price": 1099, "originalPrice": 1099, "image": "", "weight": "Pack of 76", "discount": "" },
  { "id": "bb-3", "categoryId": "baby_care", "name": "Johnson's Baby Wipes", "price": 199, "originalPrice": 199, "image": "", "weight": "Pack of 80", "discount": "" },
  { "id": "bb-4", "categoryId": "baby_care", "name": "Himalaya Baby Lotion", "price": 185, "originalPrice": 185, "image": "", "weight": "200ml", "discount": "" },
  { "id": "bb-5", "categoryId": "baby_care", "name": "Nestlé Cerelac Wheat Apple", "price": 275, "originalPrice": 275, "image": "", "weight": "300g", "discount": "" },
  { "id": "bb-6", "categoryId": "baby_care", "name": "Johnson's Baby Shampoo", "price": 215, "originalPrice": 215, "image": "", "weight": "200ml", "discount": "" },
  { "id": "bb-7", "categoryId": "baby_care", "name": "Himalaya Baby Powder", "price": 155, "originalPrice": 155, "image": "", "weight": "200g", "discount": "" },
  { "id": "bb-8", "categoryId": "baby_care", "name": "Mamaearth Milky Soft Face Cream for Babies", "price": 199, "originalPrice": 199, "image": "", "weight": "60g", "discount": "" },
  { "id": "bb-9", "categoryId": "baby_care", "name": "Johnson's Baby Oil", "price": 225, "originalPrice": 225, "image": "", "weight": "200ml", "discount": "" },
  { "id": "bb-10", "categoryId": "baby_care", "name": "Sebamed Baby Protective Facial Cream", "price": 850, "originalPrice": 850, "image": "", "weight": "50ml", "discount": "" },
  { "id": "bb-11", "categoryId": "baby_care", "name": "LuvLap Baby Laundry Detergent", "price": 399, "originalPrice": 399, "image": "", "weight": "1L", "discount": "" },
  { "id": "bb-12", "categoryId": "baby_care", "name": "Mee Mee Soft Baby Pacifier", "price": 175, "originalPrice": 175, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "bb-13", "categoryId": "baby_care", "name": "Pampers Baby Wipes with Aloe Vera", "price": 240, "originalPrice": 240, "image": "", "weight": "Pack of 72", "discount": "" },
  { "id": "bb-14", "categoryId": "baby_care", "name": "Dexolac Stage 1 Infant Formula", "price": 450, "originalPrice": 450, "image": "", "weight": "400g", "discount": "" },
  { "id": "bb-15", "categoryId": "baby_care", "name": "Himalaya Baby Diaper Rash Cream", "price": 95, "originalPrice": 95, "image": "", "weight": "20g", "discount": "" },

  /* --- PET CARE (categoryId: pet_care) --- */
  { "id": "pc-1", "categoryId": "pet_care", "name": "Pedigree Adult Dry Dog Food - Chicken & Veg", "price": 350, "originalPrice": 350, "image": "", "weight": "1.2kg", "discount": "" },
  { "id": "pc-2", "categoryId": "pet_care", "name": "Whiskas Adult Wet Cat Food - Tuna", "price": 45, "originalPrice": 45, "image": "", "weight": "85g", "discount": "" },
  { "id": "pc-3", "categoryId": "pet_care", "name": "Drools Absolute Calcium Tablets", "price": 450, "originalPrice": 450, "image": "", "weight": "50 Units", "discount": "" },
  { "id": "pc-4", "categoryId": "pet_care", "name": "Himalaya Erina-EP Tick & Flea Shampoo", "price": 210, "originalPrice": 210, "image": "", "weight": "200ml", "discount": "" },
  { "id": "pc-5", "categoryId": "pet_care", "name": "Choostix Biskies Dog Treats", "price": 240, "originalPrice": 240, "image": "", "weight": "500g", "discount": "" },
  { "id": "pc-6", "categoryId": "pet_care", "name": "Meat Up Chicken Flavor Dog Biscuits", "price": 199, "originalPrice": 199, "image": "", "weight": "500g", "discount": "" },
  { "id": "pc-7", "categoryId": "pet_care", "name": "Pets Empire Stainless Steel Feeding Bowl", "price": 185, "originalPrice": 185, "image": "", "weight": "Medium", "discount": "" },
  { "id": "pc-8", "categoryId": "pet_care", "name": "Trixie Dog Rope Toy", "price": 299, "originalPrice": 299, "image": "", "weight": "1 Unit", "discount": "" },
  { "id": "pc-9", "categoryId": "pet_care", "name": "Sheba Rich Premium Wet Cat Food", "price": 70, "originalPrice": 70, "image": "", "weight": "70g", "discount": "" },
  { "id": "pc-10", "categoryId": "pet_care", "name": "LuvLap Pet Grooming Wipes", "price": 149, "originalPrice": 149, "image": "", "weight": "Pack of 80", "discount": "" },
  { "id": "pc-11", "categoryId": "pet_care", "name": "Captain Zack Barking Up The Tea Tree Shampoo", "price": 350, "originalPrice": 350, "image": "", "weight": "200ml", "discount": "" },
  { "id": "pc-12", "categoryId": "pet_care", "name": "Purepet Mackerel Adult Cat Dry Food", "price": 299, "originalPrice": 299, "image": "", "weight": "1.2kg", "discount": "" },
  { "id": "pc-13", "categoryId": "pet_care", "name": "JerHigh Chicken Strips Dog Treat", "price": 150, "originalPrice": 150, "image": "", "weight": "70g", "discount": "" },
  { "id": "pc-14", "categoryId": "pet_care", "name": "KONG Classic Dog Toy", "price": 999, "originalPrice": 999, "image": "", "weight": "Medium", "discount": "" },
  { "id": "pc-15", "categoryId": "pet_care", "name": "Dine Daily Cat Food Pouches", "price": 540, "originalPrice": 540, "image": "", "weight": "Pack of 12", "discount": "" },

  /* --- PUJA ESSENTIALS (categoryId: puja_essentials) --- */
  { "id": "pj-1", "categoryId": "puja_essentials", "name": "Cycle Pure Agarbatti - Three in One", "price": 60, "originalPrice": 60, "image": "", "weight": "Pack of 1", "discount": "" },
  { "id": "pj-2", "categoryId": "puja_essentials", "name": "Mangaldeep Sandalwood Incense Sticks", "price": 45, "originalPrice": 45, "image": "", "weight": "Pack of 1", "discount": "" },
  { "id": "pj-3", "categoryId": "puja_essentials", "name": "Patanjali Camphor (Kapur)", "price": 85, "originalPrice": 85, "image": "", "weight": "50g", "discount": "" },
  { "id": "pj-4", "categoryId": "puja_essentials", "name": "Soulflower Rose Essential Oil", "price": 450, "originalPrice": 450, "image": "", "weight": "15ml", "discount": "" },
  { "id": "pj-5", "categoryId": "puja_essentials", "name": "Kalash Pure Gangajal", "price": 35, "originalPrice": 35, "image": "", "weight": "250ml", "discount": "" },
  { "id": "pj-6", "categoryId": "puja_essentials", "name": "Isha Life Copper Oil Lamp", "price": 250, "originalPrice": 250, "image": "", "weight": "Small", "discount": "" },
  { "id": "pj-7", "categoryId": "puja_essentials", "name": "Cotton Wicks/Batti", "price": 30, "originalPrice": 30, "image": "", "weight": "Pack of 100", "discount": "" },
  { "id": "pj-8", "categoryId": "puja_essentials", "name": "Kalava/Moli Sacred Thread", "price": 20, "originalPrice": 20, "image": "", "weight": "Pack of 2", "discount": "" },
  { "id": "pj-9", "categoryId": "puja_essentials", "name": "Samskruti Sandalwood Paste", "price": 60, "originalPrice": 60, "image": "", "weight": "25g", "discount": "" },
  { "id": "pj-10", "categoryId": "puja_essentials", "name": "Golden Dust Matchbox", "price": 20, "originalPrice": 20, "image": "", "weight": "Pack of 10", "discount": "" },
  { "id": "pj-11", "categoryId": "puja_essentials", "name": "Fresho Marigold Flowers", "price": 50, "originalPrice": 50, "image": "", "weight": "100g", "discount": "" }
];

export const INSTA_WOW_ITEMS = [
  { id: 1, title: 'Christmas Specials', discount: 'UP TO 50% OFF' },
  { id: 2, title: 'Home Essentials', discount: 'STARTS AT ₹99' },
  { id: 3, title: 'Gillette Venus', discount: 'FLAT 15% OFF' },
  { id: 4, title: 'Winter Care', discount: 'UP TO 30% OFF' },
  { id: 5, title: 'Party Packs', discount: 'BUY 1 GET 1' },
  { id: 6, title: 'Hot Beverages', discount: 'STARTS AT ₹89' },
  { id: 7, title: 'Gifting Store', discount: 'PREMIUM PACKS' },
  { id: 8, title: 'Pet Supplies', discount: 'UP TO 20% OFF' },
];

export const PREVIOUS_ORDERS = [
  { 
    id: 'order-1', 
    title: 'Most Ordered', 
    items: [
        'https://placehold.co/100x100/orange/white?text=Snack', 
        'https://placehold.co/100x100/blue/white?text=Drink', 
        'https://placehold.co/100x100/green/white?text=Veg', 
        'https://placehold.co/100x100/purple/white?text=Sweet'
    ],
    count: 17 
  },
];

export const THEME_COLOR = '#FC8019'; // Swiggy Orange